### ISSUE TITLE
Header packages?

### ISSUE THREAD

**Issue by dmaxel** [GM-Script-Writer-62850/Ubuntu-Mainline-Kernel-Updater#14]
Seems interesting, but does this only update the kernel or does it also include the headers?

**Comment by q2dg** [comment]
What is your final decission?
Thanks!

**Comment by GM-Script-Writer-62850** [comment]
i has asked dmzxel a question, he never responded, would you like it to be optional?
adding a `--noheader` option would not be that hard or time consuming

**Comment by q2dg** [comment]
Yes, this would be perfect!

**Comment by GM-Script-Writer-62850** [comment]
Made some changes
23f3a78 cdaa7bd fa639d7

**Comment by q2dg** [comment]
Thanks!
