### ISSUE TITLE
Unable to install in Ubuntu 16.04

### ISSUE THREAD

**Issue by Schattenjager-RC** [GM-Script-Writer-62850/Ubuntu-Mainline-Kernel-Updater#16]
New Ubuntu version migrated to PHP 7, but there is no PHP 5 in repositories.
Therefore Ubuntu-Mainline-Kernel-Updater can not be installed or even started.
I tried to install PHP 7 but it did not help.

**Comment by GM-Script-Writer-62850** [comment]
Did try replacing all php5 references to php7 in the install file? i would be surprised if the script broke with php7, the installer i sure, will look into it more after work

**Comment by Schattenjager-RC** [comment]
Yes, i tried, but unfortunately with no result...

**Comment by GM-Script-Writer-62850** [comment]
this is just a guess but on line 9 try removing the number on php

**Comment by Schattenjager-RC** [comment]
Unfortunately again no result, script output says: "You did not install the dependencies".
But i installed all dependencies - curl php7.0-cli libnotify-bin

**Comment by GM-Script-Writer-62850** [comment]
on line 9 change php5 to php and on line 5 change php5-cli to php7.0-cli then will install then, but i can't seem to get the script to actually find a newer kernel, i don't have time to mess with it any more this morning, i have to debug the php script next then make it work on php5 and php7

**Comment by GM-Script-Writer-62850** [comment]
never mind missing dependency:
php7.0-xml

**Comment by Schattenjager-RC** [comment]
Ok, I just changed on line 9 php5 to php and on line 8 changed  php5-cli to php7.0-cli and also added there  php7.0-xml
And now everything works fine.
Thanks a lot)

**Comment by GM-Script-Writer-62850** [comment]
Official fix: a34558e
