### ISSUE TITLE
The script does not see the 4.6.4 kernel

### ISSUE THREAD

**Issue by Schattenjager-RC** [GM-Script-Writer-62850/Ubuntu-Mainline-Kernel-Updater#21]
I am using this script with command
`KernelUpdateChecker -r \* -no-rc`
But now it just does not offer to upgrade to the kernel version 4.6.4, although it is available for several days
[http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.6.4/](url)
It seems the problem is that the kernel directory have no Ubuntu release title in its name.

**Comment by GM-Script-Writer-62850** [comment]
the naming schematic seems to have changed
v4.6.4-yakkety is the old way
new way is
v4.6.4
i'll try to fix it later have to get ready for work now

**Comment by Schattenjager-RC** [comment]
Can you please make the script work in both cases regardless of folder names?

**Comment by GM-Script-Writer-62850** [comment]
that is what i meant by fix

**Comment by GM-Script-Writer-62850** [comment]
That should do it, if you find a issue please reopen this
there is now a cleaner looking option to replace -r \*
see help output
