### ISSUE TITLE
Readme needs to be updated

### ISSUE THREAD

**Issue by Schattenjager-RC** [GM-Script-Writer-62850/Ubuntu-Mainline-Kernel-Updater#23]
It seems that the Readme file is rather old, some options are not documented.
I think that it should be updated based on the script documentation.

**Comment by GM-Script-Writer-62850** [comment]
i should but i have not felt like it and the readme does have cover all features
only option it does not cover is `-ar` which is the same as `-r \*`

**Comment by Schattenjager-RC** [comment]
Yes, you're right.
But I just wanted to say that there is also `-h` command and other alternative commands like `--force`, `--any-release`, `--no-header` and so on)

**Comment by Schattenjager-RC** [comment]
Maybe just something like this variant)
[https://github.com/GM-Script-Writer-62850/Ubuntu-Mainline-Kernel-Updater/pull/24](url)

**Comment by GM-Script-Writer-62850** [comment]
Merged
