### ISSUE TITLE
update checker script does not report freshest versions

### ISSUE THREAD

**Issue by anterak13** [GM-Script-Writer-62850/Ubuntu-Mainline-Kernel-Updater#26]
Hi, running ubuntu 16.04,
I just noticed that the KernelUpdateChecker script somehow did not handle kernel version numbers correctly:

```bash
~$ KernelUpdateChecker -r \* -v 4.7
Run this command to install the new kernel
	/tmp/kernel-update
```

but if I inspect the `/tmp/kernel-update` contents it shows that 
```bash
WHERE="http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.7-rc5"
VER_A="4.7.0-040700rc5"
VER_B="201607110749"
VER_C="4.6.3-040603"
```
despite more recent versions being available in the 4.7.* lineage such as [http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.7.6/].

However running
```bash
~$ KernelUpdateChecker -r \* -v 4.7.6
```
or even
```bash
~$ KernelUpdateChecker -r \* -v 4.7.*
```
does not report the 4.7.6 kernel as available.

Same goes with version 4.8, rc8 is available but the script only reports 4.8rc1 as available.

**Comment by GM-Script-Writer-62850** [comment]
See issue #21 
update the script to the current version
