### ISSUE TITLE
Ubuntu 17.10 installation problem

### ISSUE THREAD

**Issue by Schattenjager-RC** [GM-Script-Writer-62850/Ubuntu-Mainline-Kernel-Updater#29]
To install this script on Ubuntu 17.10 I have to replace php-7.0 with php7.1 (cli and xml packages) in the installation file.
After that everything worked well.
Or maybe we should use php-cli and php-xml packages instead. These are older versions, but more universal solution.

**Comment by GM-Script-Writer-62850** [comment]
I thought php-cli and php-xml were meta-packages for the current version, why did i not use those? anyway i will look into it later today after work

**Comment by Schattenjager-RC** [comment]
Yes, you're absolutely right about meta-packages. Different version numbers misled me)

**Comment by Schattenjager-RC** [comment]
Updated version works fine.

**Comment by GM-Script-Writer-62850** [comment]
Sorry for not updating it when i said i would, it slipped my mind

**Comment by Schattenjager-RC** [comment]
It's alight, thanks)
