### ISSUE TITLE
since https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.7.2/ the directory layout of the ppa changed braking the script

### ISSUE THREAD

**Issue by csitarichie** [GM-Script-Writer-62850/Ubuntu-Mainline-Kernel-Updater#33]
Since the 5.7.2 kernel the directory layout of the ubuntu ppa has changed and the layout now has a directory with the architecture before the *.deb files. this change causing that the parsing the thml file does not find the dep files and the 
VER_A=""
VER_B="" 
in the generated shell script becomes empty which makes the kernel update process bake.

**Comment by GM-Script-Writer-62850** [comment]
Thanks for the report, let me know if you have any more issues

**Comment by csitarichie** [comment]
I can confirm that now the script works again.  see output bellow 

Thanks for the prompt change / fix !!!.

$ cat /tmp/kernel-update 
#!/bin/bash

echo 'Config Notes:'
echo -e '\tRejecting Release Candidates'
echo -e '\tAccepting Latest Kernel'
echo -e '\tAccepting kernels compiled for *'
echo -e '\tAccepting kernels with a version higher than 5.7.0-050700rc7-generic'
echo -e '\tAccepting generic kernels'
echo -e '\tIncluding kernel headers'

WHERE="https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.7.6/amd64/"
VER_A="5.7.6-050706"
VER_B="202006241631"
VER_C="5.7.0-050700rc7"
NoHeader=0
